"""empty message

Revision ID: 8958b736695c
Revises: 7b78101401c8
Create Date: 2018-09-04 21:05:48.971336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8958b736695c'
down_revision = '7b78101401c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('feed_url', sa.TEXT(), nullable=False),
    sa.Column('site_url', sa.TEXT(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('feed_type', sa.Integer(), nullable=False),
    sa.Column('last_processed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed')
    # ### end Alembic commands ###
