"""empty message

Revision ID: 8d91673354b2
Revises: e959205824de
Create Date: 2018-11-11 21:39:23.155499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d91673354b2'
down_revision = 'e959205824de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_saved_feed_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_saved_feed_item',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feed_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feeditem.id'], name='user_saved_feed_item_feed_item_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_saved_feed_item_user_id_fkey'),
    sa.UniqueConstraint('user_id', 'feed_item_id', name='user_saved_feed_item_user_id_feed_item_id_key')
    )
    # ### end Alembic commands ###
