"""empty message

Revision ID: a15d286e2814
Revises: 68bced903297
Create Date: 2018-10-06 15:15:49.467033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15d286e2814'
down_revision = '68bced903297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_saved_feed_item', sa.Column('feed_item_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_saved_feed_item_feeditem_id_fkey', 'user_saved_feed_item', type_='foreignkey')
    op.create_foreign_key(None, 'user_saved_feed_item', 'feeditem', ['feed_item_id'], ['id'])
    op.drop_column('user_saved_feed_item', 'feeditem_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_saved_feed_item', sa.Column('feeditem_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_saved_feed_item', type_='foreignkey')
    op.create_foreign_key('user_saved_feed_item_feeditem_id_fkey', 'user_saved_feed_item', 'feeditem', ['feeditem_id'], ['id'])
    op.drop_column('user_saved_feed_item', 'feed_item_id')
    # ### end Alembic commands ###
