"""empty message

Revision ID: aee39460f958
Revises: 8d91673354b2
Create Date: 2018-11-13 23:48:13.497291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aee39460f958'
down_revision = '8d91673354b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('savedfeeditem_user_id_fkey', 'savedfeeditem', type_='foreignkey')
    op.drop_constraint('savedfeeditem_feed_item_id_fkey', 'savedfeeditem', type_='foreignkey')
    op.create_foreign_key(None, 'savedfeeditem', 'feeditem', ['feed_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'savedfeeditem', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'savedfeeditem', type_='foreignkey')
    op.drop_constraint(None, 'savedfeeditem', type_='foreignkey')
    op.create_foreign_key('savedfeeditem_feed_item_id_fkey', 'savedfeeditem', 'feeditem', ['feed_item_id'], ['id'])
    op.create_foreign_key('savedfeeditem_user_id_fkey', 'savedfeeditem', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
