"""empty message

Revision ID: af6d18194eb0
Revises: 8958b736695c
Create Date: 2018-09-22 13:45:58.431757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6d18194eb0'
down_revision = '8958b736695c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeditem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('pubdate', sa.DateTime(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeditem')
    # ### end Alembic commands ###
