"""empty message

Revision ID: c2d464408923
Revises: 49d794d90294
Create Date: 2018-11-07 21:41:52.987785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d464408923'
down_revision = '49d794d90294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('custom_topic_feed_feed_id_fkey', 'custom_topic_feed', type_='foreignkey')
    op.drop_constraint('custom_topic_feed_custom_topic_id_fkey', 'custom_topic_feed', type_='foreignkey')
    op.create_foreign_key(None, 'custom_topic_feed', 'customtopic', ['custom_topic_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'custom_topic_feed', 'feed', ['feed_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_topic_feed', type_='foreignkey')
    op.drop_constraint(None, 'custom_topic_feed', type_='foreignkey')
    op.create_foreign_key('custom_topic_feed_custom_topic_id_fkey', 'custom_topic_feed', 'customtopic', ['custom_topic_id'], ['id'])
    op.create_foreign_key('custom_topic_feed_feed_id_fkey', 'custom_topic_feed', 'feed', ['feed_id'], ['id'])
    # ### end Alembic commands ###
