"""empty message

Revision ID: e1a4ceadb450
Revises: a15d286e2814
Create Date: 2018-10-06 15:29:34.700883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a4ceadb450'
down_revision = 'a15d286e2814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_saved_feed_item', ['user_id', 'feed_item_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_saved_feed_item', type_='unique')
    # ### end Alembic commands ###
