"""empty message

Revision ID: e959205824de
Revises: c2d464408923
Create Date: 2018-11-11 20:57:01.219546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e959205824de'
down_revision = 'c2d464408923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savedfeeditem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('feed_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feed_item_id'], ['feeditem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_item_id', 'user_id')
    )
    op.create_unique_constraint(None, 'user_feed', ['user_id', 'feed_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_feed', type_='unique')
    op.drop_table('savedfeeditem')
    # ### end Alembic commands ###
